### ISSUE TITLE
stuck on adding to cart for Best Buy

### ISSUE THREAD

**Issue by catoco** [natewong1313/bird-bot#12]
I usually leave my computer on to run for restocks on Walmart and Best Buy but have come across an issue with Best Buy that it just stays on Adding to cart and won't check out. Not sure why, am I banned on the site or something? Also, what kind of proxies do you recommend for this? Residential or DCs?

**Comment by natewong1313** [comment]
Please refer to out documentation. As far as proxies, I do not have any reccomendations.
