### ISSUE TITLE
Error Submitting Payment

### ISSUE THREAD

**Issue by jjbsbll** [natewong1313/bird-bot#2]
I tried testing on a random product and had error submitting payment.

**Comment by natewong1313** [comment]
Hi - what kind of card are u using?

**Comment by jjbsbll** [comment]
tried visa debit and visa (privacy) both resulted in the samw

**Comment by sdvaper** [comment]
same.  tried visa debit and amex.  was able to add to card but error submitting payment

**Comment by natewong1313** [comment]
Please refer to out documentation. Thanks!
