### ISSUE TITLE
Error Loading Product Page

### ISSUE THREAD

**Issue by birdbotissue** [natewong1313/bird-bot#4]
I have an error that reads, "Error Loading Product Page" for every product that I choose. Any help?

**Comment by birdbotissue** [comment]
Also getting an issue on other products that says "Error Loading Cart Items"

**Comment by birdbotissue** [comment]
I am on Windows

**Comment by mmsdw** [comment]
Same here, I'm on mac tho.

**Comment by natewong1313** [comment]
Please refer to out documentation. Thanks!
