### ISSUE TITLE
Best Buy is now aware of the bot. Walmart next. Then Amazon. Next will be the Attorney General.

### ISSUE THREAD

**Issue by Ghoulhunter00** [natewong1313/bird-bot#44]
Man, I'm sorry but your actions had terrible repercussions. You caused people to over-inflate the price beyond being reasonable. Therefore you contributed to price gouging. Mr. Wong I'd suggest taking it down before I have to interfere and report it to more than just the companies. I will see your program is blacklisted and anyone who uses it is put up for price gouging. You did good with your part of the money but others are doing it for much worst. I will report and attempt to take down people personally. Nathan Wong I'd suggest taking action with your people.

**Comment by suprattle** [comment]
u mad?

**Comment by Ghoulhunter00** [comment]
Never mad passive. I'm warning as a cybersecurity worker.

**Comment by suprattle** [comment]
can we talk privately? Not on github

**Comment by switchsnatcher** [comment]
So all you switchless people are threatening a kid? Lmao

**Comment by Ghoulhunter00** [comment]
Yes where would you like to talk. I'm willing to work with whoever to
actually make it fully legal.

**Comment by suprattle** [comment]
my discord is suprattle#0001, my twitter and Instagrams are suprattle

**Comment by Ghoulhunter00** [comment]
I'll contact you there. Just for reference I am threatening anything bad
just as I said trying to make things right.
