### ISSUE TITLE
You're 100% an A-HOLE

### ISSUE THREAD

**Issue by dennis48309** [natewong1313/bird-bot#51]
That is a pretty big issue so fix it bro!  People can't buy a Switch now due to your app.

**Comment by natewong1313** [comment]
They can buy the switch if they download bird bot

**Comment by evanmp742** [comment]
http://chng.it/QBgdgwB7 muah 😘

**Comment by devmpg** [comment]
Imagine trying to start a brigade against a 16 year old because you cant play a video game

**Comment by Mbanning117** [comment]
Hey nate don't let these guys get you down, half of them have no idea how to code or do anything you've done at 16 years old. It's impressive. And there are many many other bots out there, it's not like this is the only one. These guys need to grow up. Your gonna have a bright future dude, especially with the exposure you got in the news. Just keep doing your thing man.
