### ISSUE TITLE
Great job! 

### ISSUE THREAD

**Issue by mhegs77** [natewong1313/bird-bot#64]
Fuck this idiot. Way to not think of the consequences more than 5 seconds in front of you. Glad that people are now botting every tyoe of purchase out there. Fuck this idiot

**Comment by natewong1313** [comment]
Relax Matt, I did not invent botting. Nice to see I live in your head rent free

**Comment by mhegs77** [comment]
"live in my head rent free"
Way to talk like a 16 year old. Nope I'm actually just reading how the code
has been used now to successfully buyout essential supplies around the
world.

Good job dipshit. And it's not basic supply and demand. There's regulations
out there. JFC. I'm barely 29 but you make me hate the youth.
