### ISSUE TITLE
Best Buy check out problem

### ISSUE THREAD

**Issue by BruceLeeroy559** [natewong1313/bird-bot#8]
So for me I get the item in my cart and the very last step for processing a checkout is failed due to a payment error.  

This happens at Best Buy 

I appreciate you putting this program out for free to help us, hoping you can help resolve this issue I'm having though. I am using a master card with information and billing I've checked over already. 

![image](https://user-images.githubusercontent.com/63801010/79471874-01417b00-7fb8-11ea-8b81-7da78c5f17a7.png)

**Comment by natewong1313** [comment]
Please refer to out documentation. Thanks!
